name: Run property-based tests

on:
  push: # TODO: remove after testing
  pull_request:
  merge_group:
    types: [checks_requested]
  schedule:
    # Run every midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # manually triggered

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      networks: ${{ steps.generate-matrix.outputs.networks }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Generate network matrix
        id: generate-matrix
        run: |
          NETWORKS=$(ls k8s/networks | jq -R -s -c '. | gsub(".yaml"; "") | split("\n")[:-1]')
          echo ${NETWORKS}
          echo ::set-output name=networks::${NETWORKS}

  run-tests:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        networks: ${{ fromJSON(needs.generate-matrix.outputs.networks) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup GKE auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      -
        name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
      -
        name: Setup test env
        run: |
          if [[ ${{ github.event_name }} == "pull_request" ]]; then
            # Add a "_sha_runId" suffix to differentiate PR test runs
            TEST_SUFFIX="-prop-$(echo ${{ github.sha }} | head -c 8)-${{ github.run_id }}"
          else
            # All other workflow triggers will run the tests against persistent networks
            TEST_SUFFIX="prop"
          fi
          echo "TEST_SUFFIX=$TEST_SUFFIX" >> $GITHUB_ENV
      -
        name: Test ${{ matrix.networks }}
        working-directory: k8s/tests/scripts
        run: ./run-tests.sh ${{ matrix.networks }}
      -
        # Always cleanup resources at the end of PR test runs, whether the tests pass or fail.
        name: Delete ${{ matrix.networks }}
        if: always()
        working-directory: k8s/tests/scripts
        run: |
          if [[ ${{ github.event_name }} == "pull_request" ]]; then
            ./delete-tests.sh ${{ matrix.networks }}
          fi
