name: Run Durable tests (temp)

on:
  schedule:
    - cron: "0 * * * *" # Every hour on the hour
  workflow_dispatch: {}

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        networks:
          - keramik-ceramic-v4-dev-s
          - keramik-ceramic-v4-dev-m
          - keramik-ceramic-v4-dev-l
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Login to Public ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ env.AWS_ACCESS_KEY_ID }}
          password: ${{ env.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      -
        name: Setup GKE auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      -
        name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ vars.GKE_CLUSTER }}
          location: ${{ vars.GKE_ZONE }}
      -
        name: Test ${{ matrix.networks }}
        env:
          BUILD_TAG: latest
          TEST_SELECTOR: fast
          COMPOSEDB_ADMIN_DID_SEEDS: ${{ secrets.COMPOSEDB_ADMIN_DID_SEEDS }}
        run: |
          # Expose the Keramik ComposeDB port to the host so that the tests can connect to it
          source ./port-forward.sh "${{ matrix.networks }}"
          # If we found any Keramik ComposeDB endpoints, we'll also have Ceramic API endpoints. Add them to the config.
          if [[ -n "$COMPOSEDB_URLS" ]];
          then
            sed -i "s|COMPOSEDB_URLS.*|&$COMPOSEDB_URLS|" suite/env/.env.dev
            sed -i "s|CERAMIC_URLS.*|&$CERAMIC_URLS|" suite/env/.env.dev
          fi
          make DURABLE_ENV=dev durable-tests

  collect-results:
    name: Durable Test Results
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
