name: Run smoke tests

on:
  schedule:
    # Run every midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # manually triggered

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      networks: ${{ steps.generate-matrix.outputs.networks }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Generate network matrix
        id: generate-matrix
        run: |
          NETWORKS=$(ls k8s/networks | jq -R -s -c '. | gsub(".yaml"; "") | split("\n")[:-1]')
          echo ${NETWORKS}
          echo ::set-output name=networks::${NETWORKS}

  run-tests:
    name: Test
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        networks: ${{ fromJSON(needs.generate-matrix.outputs.networks) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup GKE auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      -
        name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
      -
        # Don't clean up networks afterward so that these tests can run longer term
        name: Test ${{ matrix.networks }}
        working-directory: k8s/tests/scripts
        run: ./run-tests.sh ${{ matrix.networks }} smoke

  collect-results:
    name: Results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
